name: Ping Pullbot

on:
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Trigger Train
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/train.yml/dispatches" \
            -d '{"ref":"main"}'
